trigger:
  branches:
    include:
      - master
      - feature/*
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.11.1
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: '951417ab-7e06-4173-862d-4b791533d2c5'

jobs:
  - template: pipeline/nuke.yml@rsg
    parameters:
      AuthNuGetFeeds:
        - name: RocketSurgeonsGuild
          source: https://nuget.pkg.github.com/RocketSurgeonsGuild/index.json
          username: $(GitHub.UserName)
          password: $(GitHub.Token)
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHubAuthVariableGroup: rsg-bot
      GitHub: true
      GitHubPackages: true
      DotNetSdk:
        - "2.x"
        - "3.x"
      NuGetVersion: "5.3.0"
      PublishNuGetPackages: 'macOS'
      Matrix:
        macOS:
          BuildName: "macOS"
          ImageName: "macOS-latest"
      EnableReleaseNotes: false